/**
 * Generates the Step-by-Step Interactive Tool Practice & Tutorial Sheet.
 * Each station gives the user a specific hands-on task to try every tool.
 * This sheet runs in Sandbox Mode (will NOT overwrite user's saved canvas).
 */
export function getDemoSheetData() {
  return {
    version: '1.0.0',
    app: 'InkFlow',
    background: {
      type: 'dot-grid',
    },
    viewport: {
      x: 50,
      y: 30,
      zoom: 0.8,
    },
    shapes: [
      // ═══════════════════════════════════════════════════════════════════
      // TOP HEADER & INSTRUCTIONS
      // ═══════════════════════════════════════════════════════════════════
      {
        id: 'tut-pill-badge',
        type: 'pill',
        x: 100,
        y: 35,
        width: 330,
        height: 36,
        style: {
          stroke: '#6366f1',
          fill: '#eef2ff',
          strokeWidth: 1.5,
          strokeStyle: 'solid',
          opacity: 1,
        },
      },
      {
        id: 'tut-pill-badge-text',
        type: 'text',
        x: 110,
        y: 44,
        width: 310,
        text: '🎯 STEP-BY-STEP TOOLS PLAYGROUND',
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: 700,
        textAlign: 'center',
        style: { stroke: '#4f46e5' },
      },
      {
        id: 'tut-header-title',
        type: 'text',
        x: 100,
        y: 85,
        width: 900,
        text: '🚀 Interactive Practice Sheet: Try Every Tool Below!',
        fontSize: 30,
        fontFamily: 'Inter',
        fontWeight: 800,
        style: { stroke: '#1e293b' },
      },
      {
        id: 'tut-header-desc',
        type: 'text',
        x: 100,
        y: 130,
        width: 900,
        text: 'Follow the 8 practice stations below to master all drawing tools. (Sandbox Mode: Nothing here is saved over your real canvas)',
        fontSize: 15,
        fontFamily: 'Inter',
        style: { stroke: '#64748b' },
      },

      // ═══════════════════════════════════════════════════════════════════
      // STATION 1: SELECT, DRAG & RESIZE (Top-Left)
      // ═══════════════════════════════════════════════════════════════════
      {
        id: 'st1-frame',
        type: 'rectangle',
        x: 100,
        y: 180,
        width: 530,
        height: 250,
        style: {
          stroke: '#6366f1',
          fill: '#f8fafc',
          strokeWidth: 1.5,
          cornerRadius: 12,
        },
      },
      {
        id: 'st1-title',
        type: 'text',
        x: 120,
        y: 195,
        width: 490,
        text: 'STATION 1: Select & Transform Tool (Press 1 or V)',
        fontSize: 15,
        fontFamily: 'Inter',
        fontWeight: 700,
        style: { stroke: '#4338ca' },
      },
      {
        id: 'st1-desc',
        type: 'text',
        x: 120,
        y: 220,
        width: 490,
        text: 'Task: Drag the purple card into the green dashed box, then resize it using corner handles!',
        fontSize: 12.5,
        fontFamily: 'Inter',
        style: { stroke: '#64748b' },
      },
      // Target box
      {
        id: 'st1-target-box',
        type: 'rectangle',
        x: 390,
        y: 260,
        width: 210,
        height: 140,
        style: {
          stroke: '#16a34a',
          fill: '#f0fdf4',
          strokeWidth: 2,
          strokeStyle: 'dashed',
          cornerRadius: 8,
        },
      },
      {
        id: 'st1-target-text',
        type: 'text',
        x: 400,
        y: 315,
        width: 190,
        text: '🎯 Drop & Resize Here',
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: 600,
        textAlign: 'center',
        style: { stroke: '#15803d' },
      },
      // Movable Card
      {
        id: 'st1-drag-card',
        type: 'rectangle',
        x: 130,
        y: 275,
        width: 170,
        height: 100,
        style: {
          stroke: '#4f46e5',
          fill: '#e0e7ff',
          strokeWidth: 2,
          cornerRadius: 10,
        },
      },
      {
        id: 'st1-drag-text',
        type: 'text',
        x: 140,
        y: 305,
        width: 150,
        text: '🖐️ Drag Me!\n(Select tool 1)',
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: 600,
        textAlign: 'center',
        style: { stroke: '#3730a3' },
      },

      // ═══════════════════════════════════════════════════════════════════
      // STATION 2: FREEHAND INKING & HIGHLIGHTING (Top-Right)
      // ═══════════════════════════════════════════════════════════════════
      {
        id: 'st2-frame',
        type: 'rectangle',
        x: 660,
        y: 180,
        width: 530,
        height: 250,
        style: {
          stroke: '#d97706',
          fill: '#f8fafc',
          strokeWidth: 1.5,
          cornerRadius: 12,
        },
      },
      {
        id: 'st2-title',
        type: 'text',
        x: 680,
        y: 195,
        width: 490,
        text: 'STATION 2: Freehand Pen & Highlighting (Press 8 or P)',
        fontSize: 15,
        fontFamily: 'Inter',
        fontWeight: 700,
        style: { stroke: '#b45309' },
      },
      {
        id: 'st2-desc',
        type: 'text',
        x: 680,
        y: 220,
        width: 490,
        text: 'Task: Draw your signature or a sketch on the line below, and highlight the key words!',
        fontSize: 12.5,
        fontFamily: 'Inter',
        style: { stroke: '#64748b' },
      },
      // Signature Zone
      {
        id: 'st2-sig-line',
        type: 'line',
        x: 0,
        y: 0,
        points: [[690, 310], [920, 310]],
        style: { stroke: '#cbd5e1', strokeWidth: 2 },
      },
      {
        id: 'st2-sig-label',
        type: 'text',
        x: 690,
        y: 315,
        width: 230,
        text: '✍️ Draw signature / sketch here',
        fontSize: 11.5,
        fontFamily: 'Inter',
        style: { stroke: '#94a3b8' },
      },
      // Highlighting Target
      {
        id: 'st2-high-box',
        type: 'rectangle',
        x: 950,
        y: 260,
        width: 220,
        height: 140,
        style: {
          stroke: '#f59e0b',
          fill: '#fffbeb',
          strokeWidth: 1.5,
          cornerRadius: 8,
        },
      },
      {
        id: 'st2-high-text',
        type: 'text',
        x: 960,
        y: 280,
        width: 200,
        text: '🖍️ Highlight Practice:\n\n"InkFlow has fast 60 FPS rendering and smooth calligraphy strokes!"',
        fontSize: 12,
        fontFamily: 'Inter',
        lineHeight: 1.4,
        style: { stroke: '#78350f' },
      },

      // ═══════════════════════════════════════════════════════════════════
      // STATION 3: ERASER TOOL (Middle-Left)
      // ═══════════════════════════════════════════════════════════════════
      {
        id: 'st3-frame',
        type: 'rectangle',
        x: 100,
        y: 460,
        width: 530,
        height: 250,
        style: {
          stroke: '#ef4444',
          fill: '#f8fafc',
          strokeWidth: 1.5,
          cornerRadius: 12,
        },
      },
      {
        id: 'st3-title',
        type: 'text',
        x: 120,
        y: 475,
        width: 490,
        text: 'STATION 3: Eraser & Slicing Tool (Press 0 or E)',
        fontSize: 15,
        fontFamily: 'Inter',
        fontWeight: 700,
        style: { stroke: '#dc2626' },
      },
      {
        id: 'st3-desc',
        type: 'text',
        x: 120,
        y: 500,
        width: 490,
        text: 'Task: Press [E], then click or drag across these 3 colorful shapes to delete or slice them!',
        fontSize: 12.5,
        fontFamily: 'Inter',
        style: { stroke: '#64748b' },
      },
      // Target shapes to erase
      {
        id: 'st3-erase-rect',
        type: 'rectangle',
        x: 130,
        y: 540,
        width: 100,
        height: 90,
        style: {
          stroke: '#dc2626',
          fill: '#fee2e2',
          strokeWidth: 2,
          cornerRadius: 8,
        },
      },
      {
        id: 'st3-erase-rect-lbl',
        type: 'text',
        x: 135,
        y: 575,
        width: 90,
        text: '❌ Erase Me',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 600,
        textAlign: 'center',
        style: { stroke: '#991b1b' },
      },

      {
        id: 'st3-erase-circle',
        type: 'circle',
        x: 260,
        y: 540,
        width: 90,
        height: 90,
        style: {
          stroke: '#ea580c',
          fill: '#ffedd5',
          strokeWidth: 2,
        },
      },
      {
        id: 'st3-erase-circle-lbl',
        type: 'text',
        x: 265,
        y: 575,
        width: 80,
        text: '❌ Erase Me',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 600,
        textAlign: 'center',
        style: { stroke: '#9a3412' },
      },

      {
        id: 'st3-erase-star',
        type: 'star',
        x: 380,
        y: 540,
        width: 95,
        height: 95,
        style: {
          stroke: '#ca8a04',
          fill: '#fef9c3',
          strokeWidth: 2,
        },
      },
      {
        id: 'st3-erase-star-lbl',
        type: 'text',
        x: 380,
        y: 575,
        width: 95,
        text: '❌ Erase Me',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 600,
        textAlign: 'center',
        style: { stroke: '#854d0e' },
      },

      // ═══════════════════════════════════════════════════════════════════
      // STATION 4: SMART CONNECTORS & ARROWS (Middle-Right)
      // ═══════════════════════════════════════════════════════════════════
      {
        id: 'st4-frame',
        type: 'rectangle',
        x: 660,
        y: 460,
        width: 530,
        height: 250,
        style: {
          stroke: '#0891b2',
          fill: '#f8fafc',
          strokeWidth: 1.5,
          cornerRadius: 12,
        },
      },
      {
        id: 'st4-title',
        type: 'text',
        x: 680,
        y: 475,
        width: 490,
        text: 'STATION 4: Smart Connectors & Arrows (Press 7 or A)',
        fontSize: 15,
        fontFamily: 'Inter',
        fontWeight: 700,
        style: { stroke: '#0e7490' },
      },
      {
        id: 'st4-desc',
        type: 'text',
        x: 680,
        y: 500,
        width: 490,
        text: 'Task: Press [7] (Arrow), drag from Client node to Server node. Then drag nodes to see auto-anchoring!',
        fontSize: 12.5,
        fontFamily: 'Inter',
        style: { stroke: '#64748b' },
      },
      // Client Node
      {
        id: 'st4-client-node',
        type: 'rectangle',
        x: 690,
        y: 550,
        width: 140,
        height: 70,
        style: {
          stroke: '#0891b2',
          fill: '#cffafe',
          strokeWidth: 2,
          cornerRadius: 8,
        },
      },
      {
        id: 'st4-client-text',
        type: 'text',
        x: 700,
        y: 575,
        width: 120,
        text: '📱 Mobile Client',
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: 600,
        textAlign: 'center',
        style: { stroke: '#155e75' },
      },
      // Server Node
      {
        id: 'st4-server-node',
        type: 'rectangle',
        x: 1020,
        y: 550,
        width: 145,
        height: 70,
        style: {
          stroke: '#7c3aed',
          fill: '#ede9fe',
          strokeWidth: 2,
          cornerRadius: 8,
        },
      },
      {
        id: 'st4-server-text',
        type: 'text',
        x: 1030,
        y: 575,
        width: 125,
        text: '☁️ Cloud Gateway',
        fontSize: 13,
        fontFamily: 'Inter',
        fontWeight: 600,
        textAlign: 'center',
        style: { stroke: '#5b21b6' },
      },
      // Prompt Text in between
      {
        id: 'st4-prompt-text',
        type: 'text',
        x: 845,
        y: 575,
        width: 160,
        text: '👉 Draw Arrow (7) Here ➔',
        fontSize: 11.5,
        fontFamily: 'Inter',
        fontWeight: 600,
        textAlign: 'center',
        style: { stroke: '#0891b2' },
      },

      // ═══════════════════════════════════════════════════════════════════
      // STATION 5: TYPOGRAPHY & MULTI-FONTS (Bottom-Left)
      // ═══════════════════════════════════════════════════════════════════
      {
        id: 'st5-frame',
        type: 'rectangle',
        x: 100,
        y: 740,
        width: 530,
        height: 250,
        style: {
          stroke: '#16a34a',
          fill: '#f8fafc',
          strokeWidth: 1.5,
          cornerRadius: 12,
        },
      },
      {
        id: 'st5-title',
        type: 'text',
        x: 120,
        y: 755,
        width: 490,
        text: 'STATION 5: Text Formatting & Fonts (Press 9 or T)',
        fontSize: 15,
        fontFamily: 'Inter',
        fontWeight: 700,
        style: { stroke: '#15803d' },
      },
      {
        id: 'st5-desc',
        type: 'text',
        x: 120,
        y: 780,
        width: 490,
        text: 'Task: Double-click either text box below to edit text, change font family, or make it Bold!',
        fontSize: 12.5,
        fontFamily: 'Inter',
        style: { stroke: '#64748b' },
      },
      // Text sample 1
      {
        id: 'st5-sample-1',
        type: 'text',
        x: 130,
        y: 820,
        width: 220,
        text: 'Double click me!\nFont: Architects Daughter\nDrafting formula: E = mc²',
        fontSize: 14,
        fontFamily: 'Architects Daughter',
        style: { stroke: '#b45309' },
      },
      // Text sample 2
      {
        id: 'st5-sample-2',
        type: 'text',
        x: 370,
        y: 820,
        width: 240,
        text: 'Double click me!\nFont: Caveat (Virgil)\n"Handwritten notes feel real!"',
        fontSize: 16,
        fontFamily: 'Caveat',
        fontWeight: 600,
        style: { stroke: '#4338ca' },
      },

      // ═══════════════════════════════════════════════════════════════════
      // STATION 6: STICKY NOTES, LASER & 3D (Bottom-Right)
      // ═══════════════════════════════════════════════════════════════════
      {
        id: 'st6-frame',
        type: 'rectangle',
        x: 660,
        y: 740,
        width: 530,
        height: 250,
        style: {
          stroke: '#9333ea',
          fill: '#f8fafc',
          strokeWidth: 1.5,
          cornerRadius: 12,
        },
      },
      {
        id: 'st6-title',
        type: 'text',
        x: 680,
        y: 755,
        width: 490,
        text: 'STATION 6: Sticky Notes (S), Laser (K) & 3D Mode',
        fontSize: 15,
        fontFamily: 'Inter',
        fontWeight: 700,
        style: { stroke: '#7e22ce' },
      },
      {
        id: 'st6-desc',
        type: 'text',
        x: 680,
        y: 780,
        width: 490,
        text: 'Task: Double-click the sticky note to add an idea. Press [K] for Laser Pointer, and click 3D in statusbar!',
        fontSize: 12.5,
        fontFamily: 'Inter',
        style: { stroke: '#64748b' },
      },
      // Sticky Note
      {
        id: 'st6-sticky',
        type: 'stickyNote',
        x: 690,
        y: 820,
        width: 140,
        height: 140,
        rotation: -2,
        noteColor: '#FEF08A',
        text: '💡 Double click\nto add your note!',
        style: { fill: '#FEF08A' },
      },
      // Laser & 3D practice guide box
      {
        id: 'st6-laser-guide',
        type: 'rectangle',
        x: 860,
        y: 820,
        width: 310,
        height: 140,
        style: {
          stroke: '#c084fc',
          fill: '#faf5ff',
          strokeWidth: 1.5,
          cornerRadius: 8,
        },
      },
      {
        id: 'st6-laser-guide-text',
        type: 'text',
        x: 875,
        y: 835,
        width: 280,
        text: '🔴 Laser & 3D Demonstration:\n\n1. Press [K] and draw on the screen to see glowing laser pointer trail!\n2. Click the "3D" button in bottom statusbar to rotate the canvas!',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 500,
        lineHeight: 1.45,
        style: { stroke: '#6b21a8' },
      },
    ],
  };
}
